#
# Usage:
# docker build -t vinadoros/jdownloader -f Dockerfile-pijdl .
# docker run -d -t -u 1000 --name jdownloader -v /path:/jdownloader -v /path:/dl vinadoros/jdownloader
# https://kaistech.wordpress.com/2016/01/31/jdownloader-headless-on-raspberry-pi/
#

FROM arm32v7/openjdk:jre

VOLUME ["/jdownloader"]

WORKDIR /dl
VOLUME ["/dl"]

ENTRYPOINT ["java"]
CMD ["-Djava.awt.headless=true","-jar","/jdownloader/JDownloader.jar"]
