#
# Usage:
# docker build -t vinadoros/lpbackup -f Dockerfile-lpbackup .
# docker run -d -t --name lpbackup -v /path:/privscript vinadoros/lpbackup
#

FROM base/archlinux

RUN useradd -m -u 1000 -g users -G wheel -s /bin/bash user
RUN pacman -Syu --needed --noconfirm git python3
RUN git clone https://github.com/vinadoros/CustomScripts /opt/CustomScripts
RUN /opt/CustomScripts/Comp-ArchAUR.py

ENTRYPOINT ["bash"]
# CMD ["/privscript/1vc.sh"]
