#
# Usage:
# docker build -t r/aiso -f Dockerfile-aiso .
# docker run -dt --privileged --name aiso -v /opt/CustomScripts:/opt/CustomScripts -v /path:/aiso r/aiso
#

FROM base/archlinux

RUN pacman -Syu --noconfirm --needed archiso curl sudo git

VOLUME ["/opt/CustomScripts"]

VOLUME ["/aiso"]
WORKDIR /aiso

CMD ["/opt/CustomScripts/Arch-LiveMATEScript.sh","/aiso"]
