#
# Usage:
# docker build -t r/bondscript -f Dockerfile-pibondscr .
# docker run -d -t -u 1000 --name bondscript -v /path:/privscript -v /path:/tempfiles r/bondscript
#

FROM arm32v7/debian:jessie

RUN apt-get update && apt-get install -y bash python3 python3-pip libfontconfig1 fonts-dejavu wget
RUN pip3 install selenium
RUN wget https://github.com/wizardyhnr/phantomjs-armhf/raw/master/phantomjs-2.1.1-ubuntu-trusty-armhf -O /usr/local/bin/phantomjs; chmod a+rwx /usr/local/bin/phantomjs

VOLUME ["/privscript"]

WORKDIR /tempfiles
VOLUME ["/tempfiles"]

CMD ["python3","/privscript/combined.py","-e"]
