#
# Usage:
# docker build -t vinadoros/ubuiso -f Dockerfile-ubuiso .
# docker run -d -t --privileged --name ubuiso -v /opt/CustomScripts:/opt/CustomScripts -v /path:/ububuild vinadoros/ubuiso
#

FROM ubuntu:rolling

RUN apt update && apt install -y nano git build-essential debhelper devscripts live-build syslinux isolinux rsync
# Get and build live-build from source
# RUN git clone http://anonscm.debian.org/git/debian-live/live-build.git && \
#     cd live-build && \
#     dpkg-buildpackage -b -uc -us && \
#     cd .. && \
#     dpkg -i live-build_*.deb && \
#     mkdir /ububuild

VOLUME ["/opt/CustomScripts"]

VOLUME ["/ububuild"]
WORKDIR /ububuild

# CMD ["/opt/CustomScripts/Aubuiso.py","-n","-w","/ububuild","-o","/ububuild"]
