#
# Usage:
# docker build -t vinadoros/ubuiso -f Dockerfile-ubuiso .
# docker run -d -t --privileged --name ubuiso -v /opt/CustomScripts:/opt/CustomScripts -v /path:/ububuild vinadoros/ubuiso
#

FROM ubuntu:rolling

RUN apt update && apt install -y python3 nano git build-essential syslinux isolinux squashfs-tools genisoimage debootstrap

VOLUME ["/opt/CustomScripts"]

VOLUME ["/ububuild"]
WORKDIR /ububuild

# CMD ["/opt/CustomScripts/Aubuiso.py","-n","-w","/ububuild","-o","/ububuild"]
