#
# Usage:
# docker build -t vinadoros/ubuiso -f Dockerfile-ubuiso .
# docker run -d -t --privileged --name ubuiso -v /opt/CustomScripts:/opt/CustomScripts -v /path:/ububuild vinadoros/ubuiso
#

FROM ubuntu:rolling

RUN apt update && apt install -y nano git build-essential debhelper devscripts live-build syslinux isolinux rsync bzr gdebi-core
# Get and build live-build from source
RUN bzr branch lp:livecd-rootfs && \
   cd livecd-rootfs && \
   dpkg-buildpackage -b -uc -us && \
   cd .. && \
   gdebi -n livecd-rootfs_*.deb && \
   mkdir /ububuild

VOLUME ["/opt/CustomScripts"]

VOLUME ["/ububuild"]
WORKDIR /ububuild

CMD ["/opt/CustomScripts/Aubuiso.sh"]
