#!/usr/bin/env ruby

$script = <<SCRIPT
#!/bin/bash -x
sudo dpkg --add-architecture i386
sudo apt-get update
# sudo apt-get upgrade -y

sudo apt-get install -y python3 curl git
sudo apt-get install -y zlib1g-dev libbz2-dev libreadline6-dev libssl-dev libsqlite3-dev

# Modify sudoers to remove secure path
sudo sed -i $'/^Defaults\tenv_reset/ s/^#*/#/' /etc/sudoers
sudo sed -i $'/^Defaults\tmail_badpass/ s/^#*/#/' /etc/sudoers
sudo sed -i $'/^Defaults\tsecure_path/ s/^#*/#/' /etc/sudoers

# Install python
mkdir -p /pyenv
su vagrant -c 'curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash'

cat >> "/root/.bash_profile" <<'EOL'
export PATH="/home/vagrant/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
EOL

cat >> "/home/vagrant/.bash_profile" <<'EOL'
export PATH="/home/vagrant/.pyenv/bin:$PATH:/sbin:/usr/sbin"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
EOL

su vagrant <<'EOL'
export PATH="/home/vagrant/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
pyenv install 3.6.1
pyenv global 3.6.1
EOL

sudo bash -c "cat >/usr/local/bin/bld" <<'EOLXYZ'
#!/bin/bash -x

EOLXYZ
sudo chmod a+rwx /usr/local/bin/bld

SCRIPT

# ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |vb, config|
      vb.memory = "4096"
      config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
      config.vm.synced_folder "/", "/mf", type: "virtualbox"
    end
    config.vm.provider :libvirt do |libvirt, config|
      libvirt.memory = "4096"
      libvirt.cpus = "4"
      config.vm.synced_folder ".", "/vagrant", type: "nfs", mount_options: ['vers=4, nfsvers=4']
      config.vm.synced_folder "/", "/mf", type: "nfs", mount_options: ['vers=4, nfsvers=4']
    end
    config.vm.box = "debian/jessie64"
    config.vm.hostname = "debisovm"
    config.ssh.insert_key = true
    config.vm.provision "shell", inline: $script
end
