#!/bin/bash

select="$1"

# definition of MAC addresses
HomeServerMAC="00:e0:4c:68:5e:a2"
HomeDesktop="C8:60:00:6D:87:D8"


case $select in
sths)
	echo "Waking up HomeServer."
	#ssh -l root rmkrishna.mooo.com -p 64011 '/usr/sbin/wol 00:E0:4C:68:5E:A2 -p 7 -i 192.168.64.255'
	ssh -l root rmkrishna.mooo.com -p 64011 'ether-wake 00:E0:4C:68:5E:A2'
	;;
sphs)
	echo "Sleeping HomeServer."
	ssh -l root rmkrishna.mooo.com -p 64031 'systemctl suspend'
	;;
sthd)
	echo "Waking up HomeDesktop."
	#ssh -l root rmkrishna.mooo.com -p 64011 '/usr/sbin/wol C8:60:00:6D:87:D8 -p 7 -i 192.168.64.255'
	;;
sphd)
	echo "Sleeping HomeDesktop."
	;;
*)
  echo "No selection. Exiting."
  exit 0;
  ;;
esac
