#
# Derived from https://github.com/ConSol/docker-headless-vnc-container
# Usage:
# docker build -t vinadoros/armvnc -f Dockerfile-armvnc .
# docker run -d -t --privileged --name armvnc -p 5901:5901 -v /:/files -e 'VNC_PW=vncpassword' vinadoros/armvnc
#

FROM arm32v7/ubuntu:rolling

## Connection ports for controlling the UI:
ENV DISPLAY :1
ENV VNC_PORT 5901
EXPOSE $VNC_PORT

ENV STARTUPDIR /dockerstartup

### Envrionment config
ENV DEBIAN_FRONTEND noninteractive
ENV VNC_COL_DEPTH 24
ENV VNC_RESOLUTION 1280x1024
ENV VNC_PW vncpassword
ENV USER_PASSWORD asdf

# Add scripts
ADD ./vnc_start.sh $STARTUPDIR/vnc_start.sh
ADD ./vnc_common.sh $STARTUPDIR/vnc_common.sh
RUN chmod a+x -R $STARTUPDIR

# Install Software
RUN /dockerstartup/vnc_common.sh

# Install VNC
RUN apt-get install -y tigervnc-standalone-server && apt-get clean

CMD ["/dockerstartup/vnc_start.sh"]
