#
# Derived from https://github.com/ConSol/docker-headless-vnc-container
# Usage:
# docker build -t vinadoros/ubuvnc -f Dockerfile-ubuvnc .
# docker run -d -t --privileged --name ubuvnc -p 5901:5901 -v /path:/files -e 'VNC_PW=vncpass' vinadoros/ubuvnc
#

FROM ubuntu:rolling

## Connection ports for controlling the UI:
# VNC port:5901
ENV DISPLAY :1
ENV VNC_PORT 5901
EXPOSE $VNC_PORT

ENV STARTUPDIR /dockerstartup

### Envrionment config
ENV DEBIAN_FRONTEND noninteractive
ENV VNC_COL_DEPTH 24
ENV VNC_RESOLUTION 1280x1024
ENV VNC_PW vncpassword

### Install Software
RUN apt-get update && \
    apt-get install -y vim sudo wget nano net-tools iproute2 && \
    wget -qO- https://dl.bintray.com/tigervnc/stable/tigervnc-1.8.0.x86_64.tar.gz | tar xz --strip 1 -C / && \
    apt-get install -y firefox && \
    apt-get install -y chromium-browser chromium-codecs-ffmpeg && \
    apt-get install -y xfce4 xterm xfce4-terminal xfce4-whiskermenu-plugin xubuntu-default-settings && \
    apt-get purge -y pm-utils xscreensaver* && \
    # Install nss-wrapper to be able to execute image as non-root user
    apt-get install -y libnss-wrapper gettext && \
    apt-get clean -y

# Add user
RUN adduser --disabled-password -uid 1000 --gecos "" user && \
    echo "root:asdf" | chpasswd && \
    echo "user:asdf" | chpasswd && \
    usermod -aG sudo,video,disk,tty user

# Configure startup
ADD ./vnc_start.sh $STARTUPDIR/vnc_start.sh
RUN find $STARTUPDIR  -name '*.sh' -exec chmod a+x {} +

CMD ["/dockerstartup/vnc_start.sh"]
