#
# Derived from https://github.com/ConSol/docker-headless-vnc-container
# Usage:
# docker build -t vinadoros/ubuvnc -f Dockerfile-ubuvnc .
# docker run -d -t --privileged --name ubuvnc -p 5901:5901 -v /path:/files vinadoros/ubuvnc
#

FROM ubuntu:rolling

## Connection ports for controlling the UI:
# VNC port:5901
ENV DISPLAY :1
ENV VNC_PORT 5901
EXPOSE $VNC_PORT

ENV HOME /headless
ENV STARTUPDIR /dockerstartup
WORKDIR $HOME

### Envrionment config
ENV DEBIAN_FRONTEND noninteractive
ENV NO_VNC_HOME $HOME/noVNC
ENV VNC_COL_DEPTH 24
ENV VNC_RESOLUTION 1280x1024
ENV VNC_PW vncpassword

### Install Software
RUN apt-get update && \
    apt-get install -y vim sudo wget nano net-tools iproute2 && \
    wget -qO- https://dl.bintray.com/tigervnc/stable/tigervnc-1.8.0.x86_64.tar.gz | tar xz --strip 1 -C / && \
    apt-get install -y firefox && \
    apt-get install -y chromium-browser chromium-codecs-ffmpeg && \
    apt-get install -y xfce4 xterm xfce4-terminal xfce4-whiskermenu-plugin xubuntu-default-settings && \
    apt-get purge -y pm-utils xscreensaver* && \
    # Install nss-wrapper to be able to execute image as non-root user
    apt-get install -y libnss-wrapper gettext && \
    apt-get clean -y

# Add user
RUN adduser --disabled-password --gecos "" user && \
    echo "root:asdf" | chpasswd && \
    echo "user:asdf" | chpasswd && \
    usermod -aG sudo user

# Configure Software
RUN echo "CHROMIUM_FLAGS='--no-sandbox --start-maximized --user-data-dir'" > "$HOME/.chromium-browser.init"

### configure startup
ADD ./vnc_startup.sh $STARTUPDIR/vnc_startup.sh
RUN find $STARTUPDIR  -name '*.sh' -exec chmod a+x {} +
RUN chmod a+rwx -R /headless

USER 1984

CMD ["/dockerstartup/vnc_startup.sh","--tail-log"]
